import React, { useMemo, useState } from "react";
import { motion } from "motion/react";
import { CheckCircle2, Clock, Hash, ReceiptText, Search, XCircle } from "lucide-react";
import { useApp } from "../../../context/AppContext";
import type { Transaction } from "../../../types";

type LedgerRow = Transaction & {
  userEmail: string;
  userName: string;
};

const formatMoney = (amount: number, currency = "USD") => {
  try {
    return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);
  } catch {
    return `${currency} ${amount.toLocaleString()}`;
  }
};

const formatTimestamp = (transaction: Transaction) => {
  const raw = transaction.timestamp || transaction.date;
  const parsed = Date.parse(raw);
  if (!Number.isFinite(parsed)) return raw;
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  }).format(new Date(parsed));
};

const shortValue = (value?: string, left = 12, right = 6) => {
  if (!value) return "Not linked";
  return value.length > left + right + 3 ? `${value.slice(0, left)}...${value.slice(-right)}` : value;
};

const statusClass = (status: Transaction["status"]) => {
  if (status === "completed" || status === "approved") return "border-emerald-500/30 bg-emerald-500/10 text-emerald-400";
  if (status === "pending") return "border-yellow-500/30 bg-yellow-500/10 text-yellow-400";
  return "border-red-500/30 bg-red-500/10 text-red-400";
};

const StatusIcon: React.FC<{ status: Transaction["status"] }> = ({ status }) => {
  if (status === "completed" || status === "approved") return <CheckCircle2 size={12} />;
  if (status === "pending") return <Clock size={12} />;
  return <XCircle size={12} />;
};

const buildRows = (transactions: Transaction[]): LedgerRow[] => transactions.map(transaction => ({
  ...transaction,
  userEmail: transaction.userEmail || "",
  userName: transaction.userName || ""
}));

export const AdminTransactionsTab: React.FC = () => {
  const { adminTransactions } = useApp();
  const [statusFilter, setStatusFilter] = useState<"all" | Transaction["status"]>("all");
  const [searchQuery, setSearchQuery] = useState("");

  const transactions = useMemo(() => buildRows(adminTransactions).sort((a, b) => {
    const dateA = Date.parse(a.timestamp || a.date);
    const dateB = Date.parse(b.timestamp || b.date);
    if (Number.isFinite(dateA) && Number.isFinite(dateB) && dateA !== dateB) return dateB - dateA;
    return b.id.localeCompare(a.id);
  }), [adminTransactions]);

  const statuses = useMemo(() => Array.from(new Set(transactions.map(item => item.status))), [transactions]);

  const filtered = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    return transactions.filter(transaction => {
      const matchesStatus = statusFilter === "all" || transaction.status === statusFilter;
      if (!query) return matchesStatus;

      const searchable = [
        transaction.id,
        transaction.userId || "",
        transaction.userName,
        transaction.userEmail,
        transaction.type,
        transaction.amount.toString(),
        transaction.currency || transaction.asset,
        transaction.status,
        transaction.relatedReferenceId || "",
        transaction.timestamp || transaction.date,
        transaction.notes || ""
      ].join(" ").toLowerCase();

      return matchesStatus && searchable.includes(query);
    });
  }, [transactions, statusFilter, searchQuery]);

  const totals = useMemo(() => ({
    all: transactions.length,
    pending: transactions.filter(item => item.status === "pending").length,
    completed: transactions.filter(item => item.status === "completed" || item.status === "approved").length,
    failed: transactions.filter(item => item.status === "failed" || item.status === "rejected").length
  }), [transactions]);

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: 0.3 }} className="space-y-6">
      <div className="bg-surface border border-line rounded-2xl p-6 flex flex-col xl:flex-row items-start xl:items-center justify-between gap-5">
        <div>
          <h1 className="text-xl font-bold text-ink flex items-center gap-2">
            <ReceiptText size={20} className="text-accent" /> Financial Ledger
          </h1>
          <p className="text-xs text-muted mt-1">Search every transaction generated by user actions, payouts, and admin balance adjustments.</p>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center">
          <StatBadge label="Total" value={totals.all} />
          <StatBadge label="Pending" value={totals.pending} tone="yellow" />
          <StatBadge label="Settled" value={totals.completed} tone="green" />
          <StatBadge label="Blocked" value={totals.failed} tone="red" />
        </div>
      </div>

      <div className="bg-surface border border-line rounded-2xl overflow-hidden">
        <div className="px-5 py-4 border-b border-line flex flex-col lg:flex-row lg:items-center justify-between gap-3">
          <div>
            <h2 className="text-sm font-bold text-ink flex items-center gap-2">
              <Hash size={16} className="text-accent" /> Ledger Entries
            </h2>
            <p className="text-2xs text-muted mt-1">Each row includes transaction ID, user identity, type, amount, status, reference, and timestamp.</p>
          </div>
          <div className="flex flex-col sm:flex-row gap-2 w-full lg:w-auto">
            <div className="relative sm:w-72">
              <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
              <input
                value={searchQuery}
                onChange={event => setSearchQuery(event.target.value)}
                placeholder="Search ledger"
                className="w-full pl-9 pr-3 py-2 bg-ground border border-line rounded-lg text-xs text-ink placeholder:text-muted focus:outline-none focus:border-accent"
              />
            </div>
            <select
              value={statusFilter}
              onChange={event => setStatusFilter(event.target.value as "all" | Transaction["status"])}
              className="px-3 py-2 bg-ground border border-line rounded-lg text-xs text-ink focus:outline-none focus:border-accent"
            >
              <option value="all">All Statuses</option>
              {statuses.map(status => <option key={status} value={status}>{status}</option>)}
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1320px] text-left">
            <thead className="bg-ground/60 border-b border-line">
              <tr className="text-2xs uppercase tracking-wider text-muted">
                <th className="px-5 py-3 font-bold">Transaction ID</th>
                <th className="px-4 py-3 font-bold">User ID</th>
                <th className="px-4 py-3 font-bold">User Name</th>
                <th className="px-4 py-3 font-bold">Type</th>
                <th className="px-4 py-3 font-bold">Amount</th>
                <th className="px-4 py-3 font-bold">Currency</th>
                <th className="px-4 py-3 font-bold">Status</th>
                <th className="px-4 py-3 font-bold">Reference ID</th>
                <th className="px-5 py-3 font-bold">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line/70">
              {filtered.map(transaction => (
                <tr key={`${transaction.userEmail}-${transaction.id}`} className="hover:bg-ground/40 transition-colors">
                  <td className="px-5 py-4 text-xs font-bold text-ink" title={transaction.id}>{shortValue(transaction.id)}</td>
                  <td className="px-4 py-4 text-xs text-muted" title={transaction.userId || transaction.userEmail}>{shortValue(transaction.userId || transaction.userEmail, 14, 7)}</td>
                  <td className="px-4 py-4 text-xs font-bold text-ink">{transaction.userName}</td>
                  <td className="px-4 py-4 text-xs text-accent font-bold capitalize">{transaction.type.replace(/_/g, " ")}</td>
                  <td className="px-4 py-4 text-xs font-bold text-ink">{formatMoney(transaction.amount, transaction.currency || "USD")}</td>
                  <td className="px-4 py-4 text-xs text-muted">{transaction.currency || transaction.asset}</td>
                  <td className="px-4 py-4">
                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full border text-2xs font-bold capitalize ${statusClass(transaction.status)}`}>
                      <StatusIcon status={transaction.status} /> {transaction.status}
                    </span>
                  </td>
                  <td className="px-4 py-4 text-xs text-muted" title={transaction.relatedReferenceId || "Not linked"}>{shortValue(transaction.relatedReferenceId)}</td>
                  <td className="px-5 py-4 text-xs text-muted">{formatTimestamp(transaction)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filtered.length === 0 && (
          <div className="py-14 text-center text-sm text-muted">No transaction records match this view.</div>
        )}
      </div>
    </motion.div>
  );
};

const StatBadge: React.FC<{ label: string; value: number; tone?: "default" | "yellow" | "green" | "red" }> = ({ label, value, tone = "default" }) => {
  const toneClass = tone === "yellow"
    ? "bg-yellow-500/10 border-yellow-500/20 text-yellow-400"
    : tone === "green"
      ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
      : tone === "red"
        ? "bg-red-500/10 border-red-500/20 text-red-400"
        : "bg-ground border-line text-ink";

  return (
    <div className={`px-3 py-2 border rounded-lg min-w-[78px] ${toneClass}`}>
      <p className="text-2xs uppercase text-muted tracking-wider">{label}</p>
      <p className="text-sm font-bold">{value}</p>
    </div>
  );
};
